"""PDF report generator using reportlab platypus.

Produces a multi-page PDF covering all 11 result sections with
formatted tables, headers/footers, and a cover section.
"""

from io import BytesIO
from typing import List, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak,
)

from ..api.schemas import ExportRequest
from . import _common as C

# ── Colors ───────────────────────────────────────────────────────
BLUE = colors.HexColor("#1F4E79")
LIGHT_BLUE = colors.HexColor("#D6E4F0")
LIGHT_GREY = colors.HexColor("#F2F2F2")
WHITE = colors.white


def _header_footer(canvas, doc):
    """Draw header and footer on every page."""
    canvas.saveState()
    # Header
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(BLUE)
    canvas.drawString(0.75 * inch, letter[1] - 0.5 * inch, "Sulfidity Predictor V1")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(letter[0] - 0.75 * inch, letter[1] - 0.5 * inch,
                           f"Page {doc.page}")
    # Footer line
    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(0.75 * inch, 0.6 * inch, letter[0] - 0.75 * inch, 0.6 * inch)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(0.75 * inch, 0.45 * inch, "Generated by Sulfidity Predictor V1")
    canvas.restoreState()


def _make_kv_table(rows: List[Tuple[str, str]], col_widths=None):
    """Build a platypus Table from key-value rows."""
    if col_widths is None:
        col_widths = [2.8 * inch, 3.2 * inch]
    data = []
    for label, value in rows:
        if not label:
            data.append(["", ""])
            continue
        data.append([label, value])
    if not data:
        return None
    t = Table(data, colWidths=col_widths)
    style_cmds = [
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]
    # Alternating row colors
    for i in range(0, len(data), 2):
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), LIGHT_GREY))
    t.setStyle(TableStyle(style_cmds))
    return t


def _make_data_table(headers: List[str], rows: List[List[str]]):
    """Build a platypus Table from header + data rows."""
    data = [headers] + rows
    # Compute column widths to fill page
    avail = 7.0 * inch
    n = len(headers)
    col_w = [avail / n] * n
    t = Table(data, colWidths=col_w, repeatRows=1)
    style_cmds = [
        # Header row
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        # Data rows
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("ALIGN", (0, 1), (0, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]
    # Alternating row colors (skip header at index 0)
    for i in range(1, len(data), 2):
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), LIGHT_GREY))
    t.setStyle(TableStyle(style_cmds))
    return t


def generate_pdf_report(buffer: BytesIO, req: ExportRequest) -> None:
    """Generate a complete PDF report into the provided buffer."""
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"],
        fontSize=20, textColor=BLUE, spaceAfter=6,
    )
    section_style = ParagraphStyle(
        "SectionHeading", parent=styles["Heading2"],
        fontSize=13, textColor=BLUE, spaceBefore=16, spaceAfter=8,
    )
    spacer = Spacer(1, 12)

    elements = []

    # ── Cover / Key Inputs ───────────────────────────────────────
    elements.append(Paragraph("Sulfidity Predictor V1", title_style))
    elements.append(Paragraph("Calculation Report", styles["Heading3"]))
    elements.append(spacer)
    t = _make_kv_table(C.get_key_inputs_rows(req))
    if t:
        elements.append(t)

    # ── 1. Sulfidity ─────────────────────────────────────────────
    elements.append(Paragraph("1. Sulfidity Summary", section_style))
    t = _make_kv_table(C.get_sulfidity_rows(req))
    if t:
        elements.append(t)

    # ── 2. WL Quality ────────────────────────────────────────────
    elements.append(Paragraph("2. White Liquor Quality", section_style))
    t = _make_kv_table(C.get_wl_quality_rows(req))
    if t:
        elements.append(t)

    # ── 3. Makeup ────────────────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("3. Makeup Chemical Requirements", section_style))
    t = _make_kv_table(C.get_makeup_rows(req))
    if t:
        elements.append(t)

    # ── 4. Recovery Boiler ───────────────────────────────────────
    elements.append(Paragraph("4. Recovery Boiler", section_style))
    t = _make_kv_table(C.get_recovery_boiler_rows(req))
    if t:
        elements.append(t)

    # ── 5. Mass Balance ──────────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("5. Mass Balance", section_style))
    t = _make_kv_table(C.get_mass_balance_rows(req))
    if t:
        elements.append(t)

    # ── 6. Inventory ─────────────────────────────────────────────
    elements.append(Paragraph("6. Tank Inventory", section_style))
    t = _make_kv_table(C.get_inventory_rows(req))
    if t:
        elements.append(t)

    # ── 7. Element Tracking ──────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("7. Na/S Tracking by Unit Operation", section_style))
    op_rows = C.get_unit_operations_rows(req)
    if op_rows:
        elements.append(_make_data_table(C.get_unit_operations_headers(), op_rows))

    # ── 8. Loss Table ────────────────────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("8. Soda & Sulfur Losses", section_style))
    loss_rows = C.get_loss_table_rows(req)
    if loss_rows:
        elements.append(_make_data_table(C.get_loss_table_headers(), loss_rows))

    # ── 9. Chemical Additions ────────────────────────────────────
    elements.append(Paragraph("9. Chemical Additions", section_style))
    ca_rows = C.get_chemical_additions_rows(req)
    if ca_rows:
        elements.append(_make_data_table(C.get_chemical_additions_headers(), ca_rows))

    # ── 10. Sensitivity (optional) ───────────────────────────────
    elements.append(PageBreak())
    elements.append(Paragraph("10. Sensitivity Analysis", section_style))
    sens_rows = C.get_sensitivity_rows(req.sensitivity_items)
    if sens_rows:
        elements.append(_make_data_table(C.get_sensitivity_headers(), sens_rows))
    else:
        elements.append(Paragraph("No sensitivity data included in this report.",
                                  styles["Normal"]))

    # ── 11. Guidance ─────────────────────────────────────────────
    elements.append(Paragraph("11. Operational Guidance", section_style))
    guid_rows = C.get_guidance_rows(req)
    if guid_rows:
        elements.append(_make_data_table(C.get_guidance_headers(), guid_rows))
    else:
        elements.append(Paragraph("No guidance items.", styles["Normal"]))

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
